config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  get 'posts/listview'
  get 'menu_items/listview'
  resources :menu_items
  resources :posts
  get 'index/index'
  root 'index#index'
  get 'admin', :controller => :admin, :action => :index
  get 'admin/save-schedule'
  post 'admin/save-schedule'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  source Rails.root.join("config/app.yml")
  namespace Rails.env
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
  def save_schedule
    Setting.schedule = params[:schedule]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  layout 'index'
  def index
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  layout 'index', :only => [:listview]
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]

  # GET /menu_items
  # GET /menu_items.json
  def index
    @menu_items = MenuItem.all
    respond_to do |format|
      format.html {}
      format.json { render json: @menu_items, layout: false}
    end
  end

  def listview
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show
    respond_to do |format|
      format.html {}
      format.json { render json: MenuItem.find(params[:id]), layout: false}
    end
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items
  # POST /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully created.' }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1
  # PATCH/PUT /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: 'Menu item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_item_params
      params.require(:menu_item).permit(:name, :price)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  layout 'index', :only => [:listview]
  http_basic_authenticate_with name: "gibsonek", password: "securepassword", only: :new

  def listview
  end
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    respond_to do |format|
      format.html {}
      format.json { render json: @posts, layout: false}
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    respond_to do |format|
      format.html {}
      format.json { render json: Post.find(params[:id]), layout: false}
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :content)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:name, :contents, :notes)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/admin/index.slim
- content_for :title, "Admin control panel"

javascript:
  $(document).ready(function() {
    $('select').material_select();
  });

h3 Set schedule
form method="get" action="/admin/save-schedule"
  .input-field
    select name="schedule" = options_from_collection_for_select Schedule.all, :id, :name
  button class="waves-effect waves-light btn" type="submit" Submit

app/views/admin/save_schedule.slim
- content_for :title, "Redirecting..."

javascript:
  window.onload = function () {
    window.location.replace("/admin");
  }

p Saved. Redirecting to <a href="/admin">/admin</a>

app/views/index/index.html.slim
javascript:
  window.onload = function () {
    setInterval(function () {
      //document.getElementById('postfeed').src = document.getElementById('postfeed').src
      $.getJSON('/posts.json', function(data) {
        var html_string = "";
        data.reverse();
        for (var i = 0; i < data.length; i++) {
          html_string += "<p>"
          html_string += "<strong>";
          html_string += data[i]["title"];
          html_string += "</strong> <br> by ";
          html_string += data[i]["author"];
          html_string += " at ";
          d = new Date(data[i]["created_at"]);
          html_string += d.toLocaleDateString() + " " + d.toLocaleTimeString();
          html_string += "<br />";
          html_string += data[i]["content"];
          html_string += "</p>";
        }
        document.getElementById('postfeed').innerHTML = html_string;
      });
      $.getJSON('/menu_items.json', function(data) {
        var html_string = "";
        for (var i = 0; i < data.length; i++) {
          html_string += "<p style=\"padding:0;margin:0\">"
          html_string += "<strong>";
          html_string += data[i]["name"];
          html_string += "</strong> - $";
          var price = parseInt(data[i]["price"]);
          html_string += Math.floor(price / 100);
          html_string += "."
          html_string += ("00" + (price % 100)).slice(-2);
          html_string += "</p>";
        }
        document.getElementById('menufeed').innerHTML = html_string;
      });
    }, 1 * 1000)
  }
.row
  center style="margin-top:16px"
    img src="/ge-logo-image.png" height="72px" style="vertical-align: middle;"
    img src="/ge-logo-words.png" height="72px" style="vertical-align: middle;"
    span style="font-size:48px;margin:0;padding:0;vertical-align:middle;font-weight:300" &nbsp;| Commons Dashboard
.row
  .col.s5
    .row
      .section height="100%"
        h5 Lunch Menu
        div height="100%" width="100%" seamless="seamless" style="border:0" id="menufeed"
    .row
      .section
        h5 Announcements
        div height="100%" width="100%" seamless="seamless" style="border:0" id="postfeed"
  .col.s7
    .section
      .row
        iframe width="100%" height="525px" seamless="seamless" style="border:0" src="http://events.gibsonek.org/commonsoverview.php"
      .row
        figure
          img src="/Conference.jpeg" width="150px"
          figcaption.center-align Conference
        figure
          img src="/200.jpeg" width="150px"
          figcaption.center-align Room 200
        figure
          img src="/201.jpeg" width="150px"
          figcaption.center-align Room 201
        figure
          img src="/203.jpeg" width="150px"
          figcaption.center-align Room 203
        figure
          img src="/204.jpeg" width="150px"
          figcaption.center-align Room 204

app/views/layouts/application.slim
doctype html
html
  head
    title = yield :title
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
  body
    header.page_header
      .container
        .section
          h2 = yield :title
    main
      .container = yield

app/views/layouts/index.slim
doctype html
html
  head
    meta http-equiv="refresh" content="1800"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
  body style="margin: 0% 5%;"
    = yield

app/views/menu_items/_form.html.slim
= form_for @menu_item do |f|
  - if @menu_item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@menu_item.errors.count, "error")} prohibited this menu_item from being saved:"
      ul
        - @menu_item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price, "Price (cents)"
    = f.number_field :price
  .actions = f.submit

app/views/menu_items/edit.html.slim
- content_for :title, "Editing Menu Item"

== render 'form'

= link_to 'Show', @menu_item
'|
= link_to 'Back', menu_items_path

app/views/menu_items/index.html.slim
- content_for :title, "Listing menu items"

table
  thead
    tr
      th Name
      th Price
      th
      th
      th

  tbody
    - @menu_items.each do |menu_item|
      tr
        td = menu_item.name
        td = menu_item.price
        td = link_to 'Show', menu_item
        td = link_to 'Edit', edit_menu_item_path(menu_item)
        td = link_to 'Destroy', menu_item, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Menu item', new_menu_item_path

app/views/menu_items/listview.slim
- MenuItem.all.each do |p|
  p style="padding:0;margin:0"
    strong = p.name
    | &nbsp;-&nbsp;
    = "$#{p.price / 100}.#{(p.price % 100).to_s.rjust 2, ?0}"

app/views/menu_items/new.html.slim
- content_for :title, "New Menu Item"

== render 'form'

= link_to 'Back', menu_items_path

app/views/menu_items/show.html.slim
p#notice = notice

p
  strong Name:
  = @menu_item.name
p
  strong Price:
  = @menu_item.price

= link_to 'Edit', edit_menu_item_path(@menu_item)
'|
= link_to 'Back', menu_items_path

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field.input-field
    = f.label :title, class: "active"
    = f.text_field :title
  .field.input-field
    = f.label :author, class: "active"
    = f.text_field :author
  .field.input-field
    = f.label :content, class: "active"
    = f.text_area :content, class: "materialize-textarea active"
  .actions
    button type="submit" class="waves-effect waves-light btn" Submit

app/views/posts/edit.html.slim
- content_for :title, "Editing post"

== render 'form'

= link_to 'Show', @post, class: "waves-effect waves-light btn", style: "margin-right: 10px"
= link_to 'Back', posts_path, class: "waves-effect waves-light btn"

app/views/posts/index.html.slim
- content_for :title, "Listing posts"

table
  thead
    tr
      th Title
      th Author
      th Content
      th
      th
      th

  tbody
    - @posts.each do |post|
      tr
        td = post.title
        td = post.author
        td = post.content
        td = link_to 'pageview', post, class: "material-icons", style: "color: black"
        td = link_to 'create', edit_post_path(post), class: "material-icons", style: "color: black"
        td = link_to 'delete', post, data: { confirm: 'Are you sure?' }, method: :delete, class: "material-icons", style: "color: black"

br

= link_to 'New Post', new_post_path, class: "waves-effect waves-light btn"

app/views/posts/listview.slim
- Post.all.reverse.each do |p|
  p
    strong = p.title
    | &nbsp;by&nbsp;
    = p.author
    | &nbsp;at&nbsp;
    = p.created_at
    br
    = p.content

app/views/posts/new.html.slim
- content_for :title, "New post"

== render 'form'

= link_to 'Back', posts_path, class: "waves-effect waves-light btn"

app/views/posts/show.html.slim
p#notice = notice

p
  strong Title:&nbsp;
  = @post.title
p
  strong Author:&nbsp;
  = @post.author
p
  strong Content:&nbsp;
  = @post.content

= link_to 'Edit', edit_post_path(@post), class: "waves-effect waves-light btn", style: "margin-right: 10px"
= link_to 'Back', posts_path, class: "waves-effect waves-light btn"

app/views/schedules/_form.html.slim
= form_for @schedule do |f|
  - if @schedule.errors.any?
    #error_explanation
      h2 = "#{pluralize(@schedule.errors.count, "error")} prohibited this schedule from being saved:"
      ul
        - @schedule.errors.full_messages.each do |message|
          li = message

  .field.input-field
    = f.label :name
    = f.text_field :name
  .field.input-field
    = f.label :contents
    = f.text_area :contents, class: "materialize-textarea"
  .field.input-field
    = f.label :notes
    = f.text_field :notes
  .actions = f.submit

app/views/schedules/edit.html.slim
- content_for :title, "Editing schedule"

== render 'form'

= link_to 'Show', @schedule
'|
= link_to 'Back', schedules_path

app/views/schedules/index.html.slim
- content_for :title, "Listing schedules"

table
  thead
    tr
      th Name
      th Contents
      th Notes
      th
      th
      th

  tbody
    - @schedules.each do |schedule|
      tr
        td = schedule.name
        td = schedule.contents
        td = schedule.notes
        td = link_to 'Show', schedule
        td = link_to 'Edit', edit_schedule_path(schedule)
        td = link_to 'Destroy', schedule, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Schedule', new_schedule_path

app/views/schedules/new.html.slim
- content_for :title, "New schedule"

== render 'form'

= link_to 'Back', schedules_path

app/views/schedules/show.html.slim
p#notice = notice

p
  strong Name:
  = @schedule.name
p
  strong Contents:
  = @schedule.contents
p
  strong Notes:
  = @schedule.notes

= link_to 'Edit', edit_schedule_path(@schedule)
'|
= link_to 'Back', schedules_path